MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    # provides a route to get all the articles for a given magazine.
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    # provides a route to get all the articles for a given magazine.
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

end

MusicApp/app/models/album.rb
class Album < ApplicationRecord

    validates :title, :year, presence:true

    validates :version, inclusion: {in: %w(studio live)}

    belongs_to :band,
        foreign_key:band:id,
        class_name: :Band

    has_many :tracks,
        foreign_key: :album_id,
        class_name: :Track

end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence:true

    has_many :albums,
        foreign_key: :band_id,
        class_name: :album

    has_many :tracks,
        through: :albums,
        source: :tracks

end

MusicApp/app/models/track.rb
class Track < ApplicationRecord

    validates :version, inclusion: {in: %w(regular bonus)}


    belongs_to :album,
        foreign_key: :album_id,
        class_name: :Album


    
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
   attr_reader :password

   validates :email, presence:true, uniqueness:true
   validates :password, length: {minimum: 6}, allow_nil:true
   validates :password_digest, presence:true
   validates :session_token, presence:true, uniqueness:true

   after_initialize :ensure_session_token


# F self.find by credentials
# I is_password?
# G self.generate_session_token!
# V validations
# A  attr_reader pw
# P password=
# E ensure_session_token
# R reset_session_token!


def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
end

def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
end


def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
end

def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
end

private 
def ensure_session_token
    self.session_token ||=SecureRandom.urlsafe_base64(16)
end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def create
        @album = Album.new(album_params)
        @album.save
        if @album.save 
            redirect_to album_url
        else
            flash[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find_by([params[:name])
        render :edit
    end

    def destroy
        @album = Album.find_by(params[:name])
        @album.destroy
        redirect_to album_url
    end

    def new
        @album = Album.new
        render :new
    end

    private

    def album_params
        params.require(:album).permit(:band_id, :title, :year, :version)
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?


    private
    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def ensure_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout_user!
        current_user.reset_session_token!
        session[:session_token] = nil
    end



end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index 
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        @band.save
        if @band.save 
            redirect_to band_url
        else
            flash[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def edit
        @band = Band.find_by(params[:name])
        render :edit
    end

    def destroy
        @band = Band.find_by(params[:name])
        @band.destroy
        redirect_to band_url
    end

    def new
        @band = Band.new
        render :new
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
        #usually @user = User.new
        render :new
    end

    def create #login
        user = User.find_by_credentials(
            params[:user][:email], params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Incorrect username or password"]
            render :new
        else
            login(user)
            redirect_to bands_url
        end
    end

    def destroy
        logout_user!

        redirect_to new_session_url
        
    end



end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

    def index 
        @tracks = Track.all
        render :index
    end

    def create
        @track = track.new(track_params)
        @track.save
        if @track.save 
            redirect_to tracks_url
        else
            flash[:errors] = @track.errors.full_messages
            render :new
        end
    end

    def edit
        @track = Track.find_by([params[:name])
        render :edit
    end

    def destroy
        @track = Track.find_by(params[:name])
        @track.destroy
        redirect_to tracks_url
    end

    def new
        @track = Track.new
        render :new
    end

    private

    def track_params
        params.require(:album).permit(:album_id, :title, :ord, :lyrics, :version)
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new
        render :new
    end

    def create #signup
        @user = User.new(user_params)
        user = @user.save
        if user 
            login(@user)
            redirect_to bands_url
        else
            flash.new[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        render :show
    end

    private

    def user_params
        params.require(:user).require(:email, :password)
    end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name"authenticity_token" value"<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= band.name %>">
  <br>
  <br>
  <% submit_text = (band.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

MusicApp/app/views/bands/edit_html.erb
<section class="page"><div class="centered-box">
    <h1>Edit band </h1>
    <%= render 'shared/error' %?
    <%= render 'form', band: @band %>
    </div>
</section>

MusicApp/app/views/bands/index.html.erb
<section class = "band-index-holder"
    <nav>
        <h1> BANDS </h1>
        <a href="new_band_url %>">
        Add a band that slaps
            <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
    </nav>
    <section class"band-index">
        <% @bands.each do |band| %>
            <div class="band-index-item">
                <div>
                    <img src = "https://superawesomevectors.com/wp-content/uploads/2015/01/flat-diamond-icon.jpg" > 
                    <br/><a href= "<#%=edit_band_url"%>">Edit band info </a>
                </div>
            </div>
        <% end %>
    </section>
</section>

MusicApp/app/views/bands/new.html.erb
<section class="page"><div class="centered-box">
    <h1>New Band</h1>

    <%= render 'shared/errors' %>
    <%= render 'form', band: @band %>
</div></section>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> MusicApp </h1>
    <nav class="main-nav">
    <div>
    <% if current_user.nil?%>
      <a href="<%= new_session_url %>"> Sign in</a>
      <a href="<%= new_user_url %>"> Sign up</a>
     
      
      
    <% else %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
    <ul>    
    <%flash[:errors].each do |error|%>
       <li> <%=error%> </li>
    <%end%>
    </ul>
<%end%>

MusicApp/app/views/users/new.html.erb
<section class="page">
    <div class="centered-box">
        <h1>New User</h1>

        <%= render 'shared/errors' %>


        <form action="<%=users_url%>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%form_authenticity_token%>">

            <label for="user_email"> Email</label>
            <input type ="text" name="user[email]" id="user_email">
            <br>
            <label for="user_password"> Password</label>
            <input type ="text" name="user[password]" id="user_password">
            <br>
            <input type="submit" value="Sign up!"> 

        </form>




    </div>
</section>